# Generated by Django 6.0.2 on 2026-02-15 20:14

# Description: Migrations class for Django Models database
# Programmer(s): Abhriroop Goel, Dylan Kneidel, Ian Lim, Kit Magar, Bryce Martin, Ibrahim Sufi 
# Created: 2026-2-15
# Revised: 2026-2-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Sprint_ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Task_ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'To-Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='BACKLOG', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='myapp.sprint')),
                ('member', models.ManyToManyField(related_name='members', to='myapp.member'))
            ],
        ),
        migrations.CreateModel(
            name = 'Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key= True, serialize=False, verbose_name='Group_ID')),
                ('name', models.CharField(max_length=100)),
                ('group_code', models.IntegerField(max_length=5))
            ]
        ),
        migrations.CreateModel(
            name = 'Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Member_ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username',models.CharField(max_length=100)),
                ('password',models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('roles', models.CharField(choices=[('PROJECT_MANAGER', 'Project Manager'), ('TEAM_MEMBER', 'Team Member')], default='TEAM_MEMBER', max_length=20)),
                ('group', models.ManyToManyField(related_name= 'group', to='myapp.group')),
                ('project', models.ManyToManyField(related_name= 'project', to='myapp.project'))


            ]
        ),
        migrations.CreateModel(
            name = 'Project',
            fields = [
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Project_ID')),
                ('name', models.CharField(max_length=100))
                ('start_date', models.DateField()),
                ('group', models.ForeignKey(blank =True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='myapp.group'))
                
            ]
        ),
        migrations.CreateModel(
            name = 'Story_Point_Estimates',
            fields = [
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Project_ID')),
                ('point_estimate', models.IntegerFieldField(max_length=4))
                ('sprint', models.ForeignKey(blank =True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint', to='myapp.sprint')),
                ('member', models.ForeignKey(blank =True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to='myapp.member'))

                
            ]
        )
    ]
