# Generated by Django 6.0.2 on 2026-02-27 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_dispute_sprintcontribution'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sprintcontribution',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sprintcontribution',
            name='member',
        ),
        migrations.RemoveField(
            model_name='sprintcontribution',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='sprintcontribution',
            name='tasks_handled',
        ),
        migrations.AddField(
            model_name='sprint',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='myapp.group'),
        ),
        migrations.DeleteModel(
            name='Dispute',
        ),
        migrations.DeleteModel(
            name='SprintContribution',
        ),
    ]
