# Generated by Django 6.0.2 on 2026-02-27 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_sprintcontribution_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accused_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_received', to='myapp.member')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_raised', to='myapp.member')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='myapp.sprint')),
                ('tasks_affected', models.ManyToManyField(blank=True, related_name='disputes', to='myapp.task')),
            ],
        ),
        migrations.CreateModel(
            name='SprintContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
                ('story_points', models.IntegerField(default=0)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_contributions', to='myapp.member')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='myapp.sprint')),
                ('tasks_handled', models.ManyToManyField(blank=True, related_name='contribution_entries', to='myapp.task')),
            ],
            options={
                'unique_together': {('member', 'sprint')},
            },
        ),
    ]
