# Generated by Django 6.0.2 on 2026-02-27 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_dispute_sprintcontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='myapp.sprintcontribution'),
        ),
    ]
