# Generated by Django 6.0.2 on 2026-03-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_task_requirements_created_by_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="ai_resolution",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Full explanation returned by the Gemini AI evaluation.",
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="ai_resolved",
            field=models.BooleanField(
                blank=True,
                help_text="AI verdict: True = resolved, False = unresolved, None = not yet evaluated.",
                null=True,
            ),
        ),
    ]
