# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_dispute_ai_resolution_dispute_ai_resolved"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="github_username",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="member",
            name="github_token",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="google_account",
            field=models.EmailField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="member",
            name="github_linked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="member",
            name="google_linked",
            field=models.BooleanField(default=False),
        ),
    ]
