# Generated by Django 6.0.2 on 2026-04-12 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_task_estimation_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprintcontribution",
            name="has_overlapping_contributions",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="ai_resolution",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="ai_resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="Discrepancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_contribution", models.IntegerField(default=-1)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discrepancies",
                        to="myapp.member",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discrepancies",
                        to="myapp.task",
                    ),
                ),
            ],
        ),
    ]
