# Generated by Django 6.0.2 on 2026-04-26 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_taskcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('LOOKS_GOOD', 'Looks good to me'), ('NEEDS_CLARIFICATION', 'Needs clarification'), ('NEEDS_MORE_DETAIL', 'Needs more detail'), ('GREAT_PROGRESS', 'Great progress')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='myapp.sprintcontribution')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_reactions', to='myapp.member')),
            ],
            options={
                'unique_together': {('contribution', 'member')},
            },
        ),
    ]
